### ISSUE TITLE
option to increase / decrease audio playback

### ISSUE THREAD

**Issue by iamtalhaasghar** [revivalistsorg/element-android#13]
### Release checklist

please also add audio playback speed 1.5 & 2x option 🙏

**Comment by msusman1** [comment]
@iamtalhaasghar Do you have any UI preference, How it should look?
Screenshot with pencil drawing will work

**Comment by iamtalhaasghar** [comment]
First we need to identify if there is some work going on or not in the upstream repo. And u should contribute this feature there if itsn't there. So that all elements forks have it and also ours 😍

**Comment by iamtalhaasghar** [comment]
have opened an issue in upstream repo, if you want you can contribute a PR there. https://github.com/element-hq/element-x-android/issues/2931 @msusman1
