### ISSUE TITLE
app not installed on some devices

### ISSUE THREAD

**Issue by iamtalhaasghar** [revivalistsorg/element-android#8]
### Steps to reproduce

1. Went to [releases page](https://github.com/therevivalists/element-android/releases/download/v0.0.1/the-revivalists-gplay-universal-release.apk)
2. downloaded `the-revivalists-gplay-universal-release.apk`
3. clicked install
4. got this error

![image](https://github.com/therevivalists/element-android/assets/46928648/8b19d5db-2778-4141-87de-2cd3074fb4d2)

#### What did you expect?
To app be installed
#### What happened instead?
App was not installed

### Your phone model

HUAWEI Y7 Prime 2018

### Operating system version

8.0.0

### Application version and app store

0.0.1 from github releases

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by iamtalhaasghar** [comment]
this bug was reported to me by one of our community member on 27-march-2024. So, i have created this bug report on his behalf. Lets see if we get similar complaints

**Comment by Muhammad-AnasKhan** [comment]
### Steps

1. Went to [releases page](https://github.com/therevivalists/element-android/releases/download/v0.0.1/the-revivalists-gplay-universal-release.apk)
2. downloaded `the-revivalists-gplay-universal-release.apk`
3. clicked install
4. Installed

![Screenshot_20240419-182033.jpg](https://github.com/therevivalists/element-android/assets/91449185/3fe0e510-9909-43db-8c2a-d4cab1c053b4)



### Outcome

#### What did you expect?
To app be installed

#### What happened instead?
App was installed

### Your phone model

HONOR 7C

### Operating system version

8.0.0

**Comment by iamtalhaasghar** [comment]
Same issue on an Redmi A1+ android 12 device, https://twitter.com/nsana1418/status/1782716103640174673

**Comment by iamtalhaasghar** [comment]
Well the app is live on play store and we havent rcvd any further such reports. Also I asked people who were having this issue; the app installs fine now on their devices.
